from dilatedRNN import drnn_classification
from bidirectionalDilatedRNN import bdrnn_classification
from regularizedRNN import reg_rnn_classification
from bidirectionalregularizedRNN import bireg_rnn_classification
